In [346]:
import pandas as pd
import numpy as np

In [347]:
patients = pd.read_csv('/data/patients.csv')
admissions = pd.read_csv("/data/admissions.csv")
diagnoses = pd.read_csv("/data/diagnoses.csv")
print("Dataset loaded")

Dataset loaded

In [348]:
print("Patients:", patients.shape)
print("Admissions:", admissions.shape)
print("Diagnoses:", diagnoses.shape)

Patients: (86400, 8)

Admissions: (120000, 17)

Diagnoses: (271341, 6)

In [376]:
print("Patients columns:")
print(patients.info())

print("\nAdmissions columns:")
print(admissions.info())

print("\nDiagnoses columns:")
print(diagnoses.info())

Patients columns:

<class 'pandas.core.frame.DataFrame'>

RangeIndex: 86400 entries, 0 to 86399

Data columns (total 8 columns):

 #   Column             Non-Null Count  Dtype

---  ------             --------------  -----

 0   patient_id         86400 non-null  object

 1   age                86400 non-null  int64

 2   gender             86400 non-null  object

 3   state              86400 non-null  object

 4   bpl_card           86400 non-null  bool

 5   insurance_type     86400 non-null  object

 6   comorbidity_count  86400 non-null  int64

 7   prev_admissions    86400 non-null  int64

dtypes: bool(1), int64(3), object(4)

memory usage: 3.4+ MB

None

Admissions columns:

<class 'pandas.core.frame.DataFrame'>

RangeIndex: 120000 entries, 0 to 119999

Data columns (total 17 columns):

 #   Column          Non-Null Count   Dtype

---  ------          --------------   -----

 0   admission_id    120000 non-null  object

 1   patient_id      120000 non-null  object

 2   admit_date      120000 non-null  object

 3   discharge_date  120000 non-null  object

 4   los_days        120000 non-null  int64

 5   admit_type      120000 non-null  object

 6   ward_type       120000 non-null  object

 7   hospital_id     120000 non-null  object

 8   discharge_type  120000 non-null  object

 9   num_procedures  120000 non-null  int64

 10  charlson_index  120000 non-null  int64

 11  hba1c           120000 non-null  float64

 12  creatinine      120000 non-null  float64

 13  haemoglobin     120000 non-null  float64

 14  systolic_bp     120000 non-null  int64

 15  readmitted_30d  120000 non-null  int64

 16  readmitted_7d   120000 non-null  int64

dtypes: float64(3), int64(6), object(8)

memory usage: 11.9+ MB

None

Diagnoses columns:

<class 'pandas.core.frame.DataFrame'>

RangeIndex: 271341 entries, 0 to 271340

Data columns (total 6 columns):

 #   Column         Non-Null Count   Dtype

---  ------         --------------   -----

 0   diag_id        271341 non-null  object

 1   admission_id   271341 non-null  object

 2   icd10_code     271341 non-null  object

 3   diag_desc      271341 non-null  object

 4   diag_rank      271341 non-null  int64

 5   diag_category  271341 non-null  object

dtypes: int64(1), object(5)

memory usage: 7.2+ MB

None

In [373]:

patients.describe()

,age,comorbidity_count,prev_admissions
count,86400.000000,86400.000000,86400.000000
mean,48.000405,1.426470,0.896076
std,21.690553,1.506211,1.083745
min,0.000000,0.000000,0.000000
25%,36.000000,0.000000,0.000000
50%,51.000000,1.000000,1.000000
75%,63.000000,2.000000,1.000000
max,95.000000,8.000000,9.000000

In [370]:
admissions.describe()

,los_days,num_procedures,charlson_index,hba1c,creatinine,haemoglobin,systolic_bp,readmitted_30d,readmitted_7d
count,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000
mean,6.852708,1.523742,1.894858,5.869862,1.070463,11.840079,134.628075,0.118417,0.008383
std,5.708269,1.542197,1.610380,1.061662,0.896135,2.171929,20.756544,0.323102,0.091176
min,1.000000,0.000000,0.000000,4.000000,0.400000,4.000000,70.000000,0.000000,0.000000
25%,3.000000,0.000000,0.000000,5.300000,0.770000,10.400000,120.000000,0.000000,0.000000
50%,5.000000,1.000000,2.000000,5.700000,0.910000,11.900000,134.000000,0.000000,0.000000
75%,9.000000,2.000000,3.000000,6.100000,1.100000,13.300000,148.000000,0.000000,0.000000
max,90.000000,15.000000,6.000000,14.300000,15.000000,18.000000,220.000000,1.000000,1.000000

In [371]:
diagnoses.describe()

,diag_rank
count,271341.000000
mean,1.926867
std,0.998618
min,1.000000
25%,1.000000
50%,2.000000
75%,3.000000
max,4.000000

In [351]:
print("\nMissing values in Patients:")
print(patients.isnull().sum())

print("\nMissing values in Admissions:")
print(admissions.isnull().sum())

print("\nMissing values in Diagnoses:")
print(diagnoses.isnull().sum())

Missing values in Patients:

patient_id           0

age                  0

gender               0

state                0

bpl_card             0

insurance_type       0

comorbidity_count    0

prev_admissions      0

dtype: int64

Missing values in Admissions:

admission_id      0

patient_id        0

admit_date        0

discharge_date    0

los_days          0

admit_type        0

ward_type         0

hospital_id       0

discharge_type    0

num_procedures    0

charlson_index    0

hba1c             0

creatinine        0

haemoglobin       0

systolic_bp       0

readmitted_30d    0

readmitted_7d     0

dtype: int64

Missing values in Diagnoses:

diag_id          0

admission_id     0

icd10_code       0

diag_desc        0

diag_rank        0

diag_category    0

dtype: int64

In [354]:
primary_diag = diagnoses[diagnoses["diag_rank"] == 1]

In [357]:
df = admissions.merge(
    patients,
    on="patient_id",
    how="left"
)

In [358]:
df = df.merge(
    primary_diag,
    on="admission_id",
    how="left"
)

In [361]:
print("\nFinal dataset shape:", df.shape)
print(df.head())

Final dataset shape: (120000, 29)

                           admission_id  ...   diag_category

0  bcb311d6-0808-498f-8ae1-11abe1fbc08e  ...       Endocrine

1  996ac6db-a192-46a0-b536-503a1c57994b  ...     Respiratory

2  cc4849fa-b740-487b-beda-3086a18273c0  ...    Neurological

3  b38cdd03-165c-428c-b221-9f1d4cf8bdeb  ...  Cardiovascular

4  6a154ec0-92cc-43f5-ada5-ede0a600ce9e  ...        Neoplasm

[5 rows x 29 columns]

In [364]:

df = df.drop([
    "admission_id",
    "patient_id",
    "diag_id",
    "admit_date",
    "discharge_date",
    "readmitted_7d"
], axis=1)

Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 396, in run_async
    await coroutine
  File "<exec>", line 62, in <module>
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 394, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 1, in <module>
  File "/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/core/frame.py", line 5399, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/core/generic.py", line 4505, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/core/generic.py", line 4546, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6934, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['admission_id', 'patient_id', 'diag_id', 'admit_date', 'discharge_date', 'readmitted_7d'] not found in axis"

In [362]:

print("\nMissing values in final dataset:")
print(df.isnull().sum())

Missing values in final dataset:

admission_id         0

patient_id           0

admit_date           0

discharge_date       0

los_days             0

admit_type           0

ward_type            0

hospital_id          0

discharge_type       0

num_procedures       0

charlson_index       0

hba1c                0

creatinine           0

haemoglobin          0

systolic_bp          0

readmitted_30d       0

readmitted_7d        0

age                  0

gender               0

state                0

bpl_card             0

insurance_type       0

comorbidity_count    0

prev_admissions      0

diag_id              0

icd10_code           0

diag_desc            0

diag_rank            0

diag_category        0

dtype: int64

In [365]:
print(df.columns)

Index(['los_days', 'admit_type', 'ward_type', 'hospital_id', 'discharge_type',

       'num_procedures', 'charlson_index', 'hba1c', 'creatinine',

       'haemoglobin', 'systolic_bp', 'readmitted_30d', 'age', 'gender',

       'state', 'bpl_card', 'insurance_type', 'comorbidity_count',

       'prev_admissions', 'icd10_code', 'diag_desc', 'diag_rank',

       'diag_category'],

      dtype='object')

In [191]:
cat_cols = ["gender", "icd10_code", "diag_category"]

df = pd.get_dummies(
    df,
    columns=cat_cols,
    drop_first=True,
    dtype=int
)

print(df.head())

   hba1c  creatinine  ...  diag_category_Perinatal  diag_category_Respiratory

0    6.3        0.86  ...                        0                          0

1    5.2        1.23  ...                        0                          1

2    5.6        0.67  ...                        0                          0

3    4.7        1.40  ...                        0                          0

4    5.0        0.94  ...                        0                          0

[5 rows x 53 columns]

In [192]:
X = df.drop("readmitted_30d", axis=1)
y = df["readmitted_30d"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (120000, 52)

y shape: (120000,)

In [193]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (96000, 52)

X_test: (24000, 52)

y_train: (96000,)

y_test: (24000,)

In [194]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [195]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    penalty="l2",
    max_iter=1000,
    random_state=42
)

In [196]:
model.fit(X_train, y_train)

In [197]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[0 0 0 0 0 0 0 0 0 1]

In [198]:
y_prob = model.predict_proba(X_test)[:, 1]

print(y_prob[:10])

[0.12149045 0.15080362 0.08421781 0.02048096 0.05998155 0.064026

 0.04293025 0.10477026 0.04026874 0.52005866]

In [377]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nConfusion Matrix:", cm)

Accuracy: 0.9987886661282961

Confusion Matrix: [[56807    57]

 [   12    86]]

In [378]:
tn, fp, fn, tp = cm.ravel()

print("True Negative (TN):", tn)
print("False Positive (FP):", fp)
print("False Negative (FN):", fn)
print("True Positive (TP):", tp)

True Negative (TN): 56807

False Positive (FP): 57

False Negative (FN): 12

True Positive (TP): 86

In [379]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.6013986013986014

Recall: 0.8775510204081632

F1 Score: 0.7136929460580912

In [380]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 0.9793876259001068